In [123]:
import numpy as np
from random import random

class MLP : 
    #default values are just to test the model , please ignore 
    def __init__(self , num_inputs= 3 , num_hidden = [3 , 3] , num_outputs=2) : 
        
        #Adding all the number of inputs to the self object
        
        self.num_inputs = num_inputs 
        self.num_hidden = num_hidden
        self.num_outputs = num_outputs
        
        #layers for mlp
    
        layers = [self.num_inputs] + self.num_hidden + [self.num_outputs] #used the [] becuase the num hidden is already
        #in matrix form 
        
        #intiate random weights 
        
        weights = []
        for i in range(len(layers) - 1) : 
            w = np.random.rand(layers[i] , layers[i+1]) #random arrays are created , 
            weights.append(w) 
        self.weights = weights
        
        
        #activations 
        activations = [] 
        for i in range(len(layers)):
            a=np.zeros(layers[i])
            activations.append(a)
        self.activations = activations
        
        # derivatives 
        
        derivatives = [] 
        for i in range(len(layers)-1):
            d=np.zeros((layers[i] , layers[i+1]))
            derivatives.append(d)
        self.derivatives = derivatives
        
        
    #neuron activation and input 
    def foward_propogate(self , inputs) : 
        
        activations= inputs 
        self.activations[0] = activations 
        for i,w in enumerate(self.weights) : 
            #calculate net inputs 
            net_inputs = np.dot(activations , w)
            #calculate the activations 
            activations = self._sigmoid(net_inputs)
            self.activations[i+1] = activations
            
            
        return activations 
    def _sigmoid(self , x ) : 
        return 1 / (1 + np.exp(-x))
    
    def back_propogate(self , error , verbose=False):
        for i in reversed(range(len(self.derivatives))):
            activations = self.activations[i+1]
            delta = error * self._sigmoid_derivative(activations)
            delta_reshaped = delta.reshape(delta.shape[0] , -1).T
            current_activation = self.activations[i] 
            current_activation_reshaped = current_activation.reshape(current_activation.shape[0] , -1)
            self.derivatives[i] = np.dot(current_activation_reshaped , delta_reshaped)
            error = np.dot(delta , self.weights[i].T)
            
            if verbose : 
                print('Derviates for W{} : {}'.format(i , self.derivatives))
        return error
    
    def gradient_descent(self , learning_rate , verbose=False):
        for i in range(len(self.weights)):
            weights = self.weights[i]
            if verbose : 
                print("Before : W{} : {}".format(i , weights))
            derivatives = self.derivatives[i]
            weights += derivatives * learning_rate
            if verbose : 
                print("After : W{} : {}".format(i , weights))
    
    def train(self , inputs , targets , epochs , learning_rate ):
        for i in range(epochs):
            sum_error = 0
            
            for j,input in enumerate(inputs):
                
                target = targets[j]
                
                op = self.foward_propogate(input)

                error = target - op
        
                self.back_propogate(error)

                self.gradient_descent(learning_rate)
 
                sum_error = sum_error + self._mse(target , op)
    
            print("Error : {} at epoch {}".format(sum_error/len(inputs), i+1) )
    
    def test(self , inputs ):
        op = self.foward_propogate(inputs)
        print("Op of the test is {}".format(op))
        
        
    def _mse(self , target , output ):
        return np.average((target - output)**2)
    
    def _sigmoid_derivative(self , x):
        return x * (1.0 - x)
        
    

In [124]:
import numpy as np
w = np.random.rand(3,3)
print(w)

[[0.95474578 0.16029372 0.78163989]
 [0.94912919 0.54039995 0.11418317]
 [0.72839728 0.60204915 0.9231772 ]]


In [125]:
#create a mlp 
mlp = MLP()
#create inputs 
inputs = np.random.rand(mlp.num_inputs)
# do foward propogations 
outputs=mlp.foward_propogate(inputs)
#results
print("The network i/p is : {} ".format(inputs)) 
print("The network o/p is : {} ".format(outputs)) 

The network i/p is : [0.38364367 0.93329119 0.39446931] 
The network o/p is : [0.82127206 0.84458156] 


In [137]:
if __name__ == "__main__":
    #create an mlp
    mlp = MLP(2, [5] , 1)
    #create dummy data
    items = np.array([[random()/2 for _ in range(2)] for _ in range(5000)])
    targets = np.array([[i[0] + i[1]] for i in items])
    
    mlp.train(items , targets , 50 , 0.5)
    #foward propogation
    mlp.test([0.45, .43])

Error : 0.027763161064259106 at epoch 1
Error : 0.002930838820240789 at epoch 2
Error : 0.0009170459269787682 at epoch 3
Error : 0.0006713334594201688 at epoch 4
Error : 0.0005892754504998832 at epoch 5
Error : 0.000541230641233819 at epoch 6
Error : 0.0005078977437871836 at epoch 7
Error : 0.00048327962566818597 at epoch 8
Error : 0.0004643094381918556 at epoch 9
Error : 0.0004491898092006889 at epoch 10
Error : 0.00043680745184126194 at epoch 11
Error : 0.0004264401793570485 at epoch 12
Error : 0.00041760021364111317 at epoch 13
Error : 0.0004099466207043413 at epoch 14
Error : 0.00040323407598198197 at epoch 15
Error : 0.00039728159939690053 at epoch 16
Error : 0.00039195276580024856 at epoch 17
Error : 0.0003871427755112017 at epoch 18
Error : 0.00038276976990275107 at epoch 19
Error : 0.0003787688544999108 at epoch 20
Error : 0.00037508789569555063 at epoch 21
Error : 0.0003716845072549737 at epoch 22
Error : 0.0003685238521212969 at epoch 23
Error : 0.0003655770137043068 at epoch

<class 'int'> 3
<class 'int'> 3
<class 'int'> 3


In [37]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])